server:
  port: 8080
spring:
  application:
    name: my-utils

  # redis相关配置
  redis:
    database: 10
    host: 47.99.218.127  # redis服务器地址
    password: wuligao      # redis密码
    port: 7000          # redis连接端口
    timeout: 6000ms       # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 200  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10     # 连接池中的最大空闲连接
        min-idle: 0      # 连接池中的最小空闲连接